name: scipy-sheets
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.13
  - ipykernel>=6.29.5
  - jupyter>=1.1.1
  - nbconvert>=7.16.6
  - numpy>=2.2.5
  - openpyxl>=3.1.5
  - pandas>=2.2.3
  - pillow>=11.2.1
  - python-calamine>=0.3.2
  - pip
  - pip:
    - odfpy>=1.4.1
    - pyspread>=2.4
